# Generated by Django 4.2.1 on 2023-05-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='isbn',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='isbn',
            name='book_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='isbn',
            name='number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
